### ISSUE TITLE
palette.pal seems to be an older version.

### ISSUE THREAD

**Issue by jbrandwood** [Kitrinx/TG16_Palette#1]
FYI, the checked-in version of palette.pal does not match the version that is generated when I compile and run the code.

Indications are that the palette.pal file in github may be from a previous version of the code, before the Sep 2020 tweaks.

Is the mismatch deliberate?

Best wishes,

John

**Comment by Kitrinx** [comment]
ill update it when I get a chance

**Comment by jbrandwood** [comment]
Thank you! :-)

**Comment by Kitrinx** [comment]
I've updated the code to apply a few cleaner implementations that I've learned since I wrote it and updated the generated palette as well.

**Comment by jbrandwood** [comment]
Thanks, I'll close this now!

Best wishes,

John
