### ISSUE TITLE
The final palette math expands it far beyond Hudson's color range.

### ISSUE THREAD

**Issue by jbrandwood** [Kitrinx/TG16_Palette#3]
FWIW, Hudson's "Character Editor", the PC-9801 graphics editing tool that they gave to developers to actually create graphics for the PC Engine, uses the RGB component values $00, $20, $40, $60, $80, $A0, $B0, $C0 (actually $0, $2, $4, $6, $8, $A, $B, $C in the PC-9801VX's 12-bit palette) .

This limits the brightest-grey for art to 75%, and not the 100% white that your palette is currently expanded to.

Changing the math on line 95 in tg16color.c from ...
	double m = (255.0/235.0) * 255.0;
to
	double m = (192.0/235.0) * 255.0;

... results in a output palette that makes the colors look much closer to what the artists were seeing on their PC-9801 monitors, and from my POV, makes the the art in PCE games look much nicer than the over-contrasted look with the current palette expansion.

**Comment by Kitrinx** [comment]
It's entirely possible to do this if you don't mind having extremely dingy whites and colors, but it's pretty unappealing on virtually all displays, and i'm not convinced this is how these colors actually appeared in the end results. It seems very unlikely to me their whites were limited to just a dingy grey.

**Comment by Kitrinx** [comment]
after having done my nes palette, the green is probably calculated very slightly wrong in tg16 palette. I think probably it would be better to keep the luma correctly limited to 255 for the srgb color space, and then desaturate the colors correctly after the fact to make the contrast less jarring.

**Comment by jbrandwood** [comment]
I understand your position based on the math, and this is your project to do with as you wish ... I thank you for all your hard work, and for releasing it publicly!

I will point out that even Artemio's vectorscope measurements don't show a 100% white signal ...
https://junkerhq.net/xrgb/index.php?title=File:07-PCE-Duo-R-GrayRamp.png

Best wishes,

John

**Comment by Kitrinx** [comment]
There's other factors involved, like auto gain control on a CRT. The image is definitely not fully saturated, however I do think white should still appear white and black should still appear black in the SRGB space, this is something the technology of then and now tries to always get right. Take a look at this generated vectorscope image from a 25% desaturated version of the palette. You can see it matches up with the capture of the original hardware nearly perfectly. Red is generated palette, green is original captures palette.
![image](https://user-images.githubusercontent.com/15653832/162632817-7f2c989d-4e11-4f06-a688-6e828f31f866.png)

**Comment by jbrandwood** [comment]
Thanks again.

Yes, the PCE was known for its de-saturated colors, even back when I bought my grey-import SuperGrafx in 1989/1990.

The math that you're using does an excellent job of recreating that, and of applying the slight green-shift to some colors in the same way that the console does on a TV.

My only dissatisfaction with the results is probably due to the particular LCD screen that I'm using.

Since you've been so kind as to make the source available, I've just tweaked the math a little, to effectively turn down the "brightness" knob a bit, so that the results look better to my old eyes on my crappy un-calibrated LCD.

I certainly don't expect you to use those numbers in your code!

I'll check-in the changes into my fork should you have any curiosity in seeing them ... but I can't do that right now because the changes that you checked-in last night won't compile because the desaturate_rgb_linear() function is missing! ;-)

Best wishes,

John

**Comment by Kitrinx** [comment]
I've actually updated the code yesterday to desaturate a bit differently, in the way I ultimately settled on for my NES palette. See if maybe it agrees with you.

**Comment by jbrandwood** [comment]
I look forward to seeing your latest changes, but am having trouble compiling the latest check-in.

$ gcc -o tg16color tg16color.c -lm
tg16color.c: In function 'yuv2rgb':
tg16color.c:88:9: warning: implicit declaration of function 'desaturate_rgb_linear' [-Wimplicit-function-declaration]
   88 |         desaturate_rgb_linear(&co, 192.0/255.0, &r1, &g1, &b1);
      |         ^~~~~~~~~~~~~~~~~~~~~
D:/retrogamedev/tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: D:\retrogamedev\tools\msys64\tmp\ccY0mlvt.o:tg16color.c:(.text+0x15883): undefined reference to `desaturate_rgb_linear'
collect2.exe: error: ld returned 1 exit status

**Comment by Kitrinx** [comment]
Sorry I forgot to add the changes to color_lib.h, should be good now

**Comment by jbrandwood** [comment]
Thank you!

I've just tested the output, and honestly, it seems a bit too desaturated now, but that may be my crappy LCD screen ... we're currently discussing that on a PC Engine fourm. ;-)

But because you've released the source, I can tweak the numbers to look best on my screen, in just the way that I would have done with the brightness/contrast/tint settings on my TV back in the 1980s!

As a programmer that's not familiar with the inner-interactions of the math that you're using, I do have to ask ... if you're expecting a TVs AGC to magnify the 90%-max-luma that Artemio measured to 100%-max-luma, would that same gain have any effect on the 25% desaturation that you're now applying?

**Comment by Kitrinx** [comment]
The idea of AGC was that very few signals of the era were perfectly to spec, but using various heuristics on the signal it could be determined how much the luma could be boosted to make the signal look appropriately bright. This usually took the form of measuring the sync signal levels and bumping the brightness based on the deviation of that from spec, but it wasn't guaranteed to work this way, or how much. Since now we have digital perfection, we can just say that white is 100% and black is 0% and have the perfect output that the analog era things strove to achieve.

**Comment by Kitrinx** [comment]
To be more clear, what I am saying is that there was no "definitive" brightness you'd get, it would vary from tv to tv, so you may as well make it perfect, since you can. This also probably varied from console to console, certainly from model to model of PCE. As for the desaturation, it matches the hues perfectly right now. You can change it to your tastes of course, but what you see is what the thing output. It's up to you how much you want to boost it to suit modern tastes.

**Comment by jbrandwood** [comment]
OK, thanks for your patience!

I don't really want to mess with the saturation if you're happy with that math, I'm far more interested in tweaking the brightness to make the image look better on my crappy LCD ... which doesn't belong in your master copy of the repository.

Thanks again, and I'll close this now.

Best wishes,

John
